<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3021f1db-173b-4667-a6b5-8dc65eed2fcb</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="config*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
   <Content Update="log.config">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
   </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.1-dev-02312" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\ICMarkets.Blockcypher.Application.DependencyInjection\ICMarkets.Blockcypher.Application.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\Application\ICMarkets.Blockcypher.Application.Interfaces\ICMarkets.Blockcypher.Application.Interfaces.csproj" />
    <ProjectReference Include="..\..\Domain\ICMarkets.Blockcypher.Domain.Types\ICMarkets.Blockcypher.Domain.Types.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ICMarkets.Blockcypher.Infrastructure.DependencyInjection\ICMarkets.Blockcypher.Infrastructure.DependencyInjection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

</Project>
