<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\ICMarkets.Blockcypher.Domain.Types\ICMarkets.Blockcypher.Domain.Types.csproj" />
    <ProjectReference Include="..\ICMarkets.Blockcypher.Application.DataObjects\ICMarkets.Blockcypher.Application.DataObjects.csproj" />
  </ItemGroup>

</Project>
